project:
  type: website
  output-dir: "Docs"

website:
  title: "blogpro"
  navbar:
    left: 
      - text: " Home" 
        href: index.qmd
      - text: "Portofolio"
        href: portofolio.qmd
      - text: "CV"
        href: cv.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

